<template>
    <div class="grid grid-cols-1 gap-6 pt-5 lg:grid-cols-2">
        <div class="form-group">
            <label class="capitalize"> {{ $t('sessionName') }} </label>
            <div>
                <div class="">
                    <input type="text" v-model="contentObject.name" class="form-input" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="capitalize"> {{ $t('date') }} </label>
            <div>
                <div class="form-input">
                    {{ contentObject.date }}
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="capitalize"> {{ $t('country') }} </label>
            <div>
                <div class="">
                    <select v-model="country_id" :placeholder="$t('country')" class="form-select text-white-dark">
                        <option v-for="item in countries" :key="item.id" :value="item.id">
                            {{ item.name }}
                        </option>
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="capitalize"> {{ $t('city') }} </label>
            <div>
                <div class="">
                    <select v-model="city_id" :disabled="!country_id" :placeholder="$t('city')" class="form-select text-white-dark">
                        <option v-for="item in cites" :key="item.id" :value="item.id">
                            {{ item.name }}
                        </option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    import { useRuntimeConfig } from '#imports';
    import { useAppStore } from '@/stores/index';
    export default {
        props: {
            contentVal: {
                require: false,
            },
        },
        data() {
            return {
                lang: useAppStore().locale,
                cites: [],
                apiUrl: useRuntimeConfig().public.apiUrl,
                countries: [],
                city_id: null,
                country_id: null,
                contentObject: {
                    has_images: 0,
                    has_videos: 0,
                    date: new Date().toISOString().slice(0, 10),
                    name: '',
                },
            };
        },
        watch: {
            contentVal() {
                if (this.contentVal && this.contentVal.length != 0) {
                    this.contentObject = this.contentVal;
                    this.country_id = this.contentVal.country_id;
                    this.city_id = this.contentVal.city_id;
                }
            },

            contentObject: {
                handler(newValue, oldValue) {
                    this.$emit('addContent', this.contentObject);
                },
                deep: true,
            },
            country_id() {
                this.cites = [];
                this.city_id = null;
                this.contentObject.country_id = this.country_id;
                this.$emit('addContent', this.contentObject);
                this.getCity();
            },
            city_id() {
                this.contentObject.city_id = this.city_id;
                this.$emit('addContent', this.contentObject);
            },
        },
        created() {
            this.getCountry();
        },
        methods: {
            async getCountry() {
                const res = [
                    {
                        id: 1,
                        name_en: 'Afghanistan',
                        name_ar: 'أفغانستان',
                        country_code: 93,
                        iso_code_2: 'AF',
                        iso_code_3: 'AFG',
                    },
                    {
                        id: 2,
                        name_en: 'Albania',
                        name_ar: 'ألبانيا',
                        country_code: 355,
                        iso_code_2: 'AL',
                        iso_code_3: 'ALB',
                    },
                    {
                        id: 3,
                        name_en: 'Algeria',
                        name_ar: 'الجزائر',
                        country_code: 213,
                        iso_code_2: 'DZ',
                        iso_code_3: 'DZA',
                    },
                    {
                        id: 4,
                        name_en: 'American Samoa',
                        name_ar: 'ساموا الأمريكية',
                        country_code: 1684,
                        iso_code_2: 'AS',
                        iso_code_3: 'ASM',
                    },
                    {
                        id: 5,
                        name_en: 'Andorra',
                        name_ar: 'أندورا',
                        country_code: 376,
                        iso_code_2: 'AD',
                        iso_code_3: 'AND',
                    },
                    {
                        id: 6,
                        name_en: 'Angola',
                        name_ar: 'أنغولا',
                        country_code: 244,
                        iso_code_2: 'AO',
                        iso_code_3: 'AGO',
                    },
                    {
                        id: 7,
                        name_en: 'Anguilla',
                        name_ar: 'أنغيلا',
                        country_code: 1264,
                        iso_code_2: 'AI',
                        iso_code_3: 'AIA',
                    },
                    {
                        id: 8,
                        name_en: 'Antarctica',
                        name_ar: 'أنتاركتيكا',
                        country_code: 0,
                        iso_code_2: 'AQ',
                        iso_code_3: 'ATA',
                    },
                    {
                        id: 9,
                        name_en: 'Antigua and Barbuda',
                        name_ar: 'أنتيغوا وبربودا',
                        country_code: 1268,
                        iso_code_2: 'AG',
                        iso_code_3: 'ATG',
                    },
                    {
                        id: 10,
                        name_en: 'Argentina',
                        name_ar: 'الأرجنتين',
                        country_code: 54,
                        iso_code_2: 'AR',
                        iso_code_3: 'ARG',
                    },
                    {
                        id: 11,
                        name_en: 'Armenia',
                        name_ar: 'أرمينيا',
                        country_code: 374,
                        iso_code_2: 'AM',
                        iso_code_3: 'ARM',
                    },
                    {
                        id: 12,
                        name_en: 'Aruba',
                        name_ar: 'أروبا',
                        country_code: 297,
                        iso_code_2: 'AW',
                        iso_code_3: 'ABW',
                    },
                    {
                        id: 13,
                        name_en: 'Australia',
                        name_ar: 'أستراليا',
                        country_code: 61,
                        iso_code_2: 'AU',
                        iso_code_3: 'AUS',
                    },
                    {
                        id: 14,
                        name_en: 'Austria',
                        name_ar: 'النمسا',
                        country_code: 43,
                        iso_code_2: 'AT',
                        iso_code_3: 'AUT',
                    },
                    {
                        id: 15,
                        name_en: 'Azerbaijan',
                        name_ar: 'أذربيجان',
                        country_code: 994,
                        iso_code_2: 'AZ',
                        iso_code_3: 'AZE',
                    },
                    {
                        id: 16,
                        name_en: 'Bahamas',
                        name_ar: 'جزر البهاما',
                        country_code: 1242,
                        iso_code_2: 'BS',
                        iso_code_3: 'BHS',
                    },
                    {
                        id: 17,
                        name_en: 'Bahrain',
                        name_ar: 'البحرين',
                        country_code: 973,
                        iso_code_2: 'BH',
                        iso_code_3: 'BHR',
                    },
                    {
                        id: 18,
                        name_en: 'Bangladesh',
                        name_ar: 'بنغلاديش',
                        country_code: 880,
                        iso_code_2: 'BD',
                        iso_code_3: 'BGD',
                    },
                    {
                        id: 19,
                        name_en: 'Barbados',
                        name_ar: 'بربادوس',
                        country_code: 1246,
                        iso_code_2: 'BB',
                        iso_code_3: 'BRB',
                    },
                    {
                        id: 20,
                        name_en: 'Belarus',
                        name_ar: 'بيلاروسيا',
                        country_code: 375,
                        iso_code_2: 'BY',
                        iso_code_3: 'BLR',
                    },
                    {
                        id: 21,
                        name_en: 'Belgium',
                        name_ar: 'بلجيكا',
                        country_code: 32,
                        iso_code_2: 'BE',
                        iso_code_3: 'BEL',
                    },
                    {
                        id: 22,
                        name_en: 'Belize',
                        name_ar: 'بليز',
                        country_code: 501,
                        iso_code_2: 'BZ',
                        iso_code_3: 'BLZ',
                    },
                    {
                        id: 23,
                        name_en: 'Benin',
                        name_ar: 'بنين',
                        country_code: 229,
                        iso_code_2: 'BJ',
                        iso_code_3: 'BEN',
                    },
                    {
                        id: 24,
                        name_en: 'Bermuda',
                        name_ar: 'برمودا',
                        country_code: 1441,
                        iso_code_2: 'BM',
                        iso_code_3: 'BMU',
                    },
                    {
                        id: 25,
                        name_en: 'Bhutan',
                        name_ar: 'بوتان',
                        country_code: 975,
                        iso_code_2: 'BT',
                        iso_code_3: 'BTN',
                    },
                    {
                        id: 26,
                        name_en: 'Bolivia',
                        name_ar: 'بوليفيا',
                        country_code: 591,
                        iso_code_2: 'BO',
                        iso_code_3: 'BOL',
                    },
                    {
                        id: 27,
                        name_en: 'Bosnia and Herzegovina',
                        name_ar: 'البوسنة والهرسك',
                        country_code: 387,
                        iso_code_2: 'BA',
                        iso_code_3: 'BIH',
                    },
                    {
                        id: 28,
                        name_en: 'Botswana',
                        name_ar: 'بوتسوانا',
                        country_code: 267,
                        iso_code_2: 'BW',
                        iso_code_3: 'BWA',
                    },
                    {
                        id: 29,
                        name_en: 'Bouvet Island',
                        name_ar: 'جزيرة بوفيت',
                        country_code: 0,
                        iso_code_2: 'BV',
                        iso_code_3: 'BVT',
                    },
                    {
                        id: 30,
                        name_en: 'Brazil',
                        name_ar: 'البرازيل',
                        country_code: 55,
                        iso_code_2: 'BR',
                        iso_code_3: 'BRA',
                    },
                    {
                        id: 31,
                        name_en: 'British Indian Ocean Territory',
                        name_ar: 'إقليم المحيط الهندي البريطاني',
                        country_code: 0,
                        iso_code_2: 'IO',
                        iso_code_3: 'IOT',
                    },
                    {
                        id: 32,
                        name_en: 'Brunei Darussalam',
                        name_ar: 'بروناي دار السلام',
                        country_code: 673,
                        iso_code_2: 'BN',
                        iso_code_3: 'BRN',
                    },
                    {
                        id: 33,
                        name_en: 'Bulgaria',
                        name_ar: 'بلغاريا',
                        country_code: 359,
                        iso_code_2: 'BG',
                        iso_code_3: 'BGR',
                    },
                    {
                        id: 34,
                        name_en: 'Burkina Faso',
                        name_ar: 'بوركينا فاسو',
                        country_code: 226,
                        iso_code_2: 'BF',
                        iso_code_3: 'BFA',
                    },
                    {
                        id: 35,
                        name_en: 'Burundi',
                        name_ar: 'بوروندي',
                        country_code: 257,
                        iso_code_2: 'BI',
                        iso_code_3: 'BDI',
                    },
                    {
                        id: 36,
                        name_en: 'Cambodia',
                        name_ar: 'كمبوديا',
                        country_code: 855,
                        iso_code_2: 'KH',
                        iso_code_3: 'KHM',
                    },
                    {
                        id: 37,
                        name_en: 'Cameroon',
                        name_ar: 'الكاميرون',
                        country_code: 237,
                        iso_code_2: 'CM',
                        iso_code_3: 'CMR',
                    },
                    {
                        id: 38,
                        name_en: 'Canada',
                        name_ar: 'كندا',
                        country_code: 1,
                        iso_code_2: 'CA',
                        iso_code_3: 'CAN',
                    },
                    {
                        id: 39,
                        name_en: 'Cape Verde',
                        name_ar: 'الرأس الأخضر',
                        country_code: 238,
                        iso_code_2: 'CV',
                        iso_code_3: 'CPV',
                    },
                    {
                        id: 40,
                        name_en: 'Cayman Islands',
                        name_ar: 'جزر كايمان',
                        country_code: 1345,
                        iso_code_2: 'KY',
                        iso_code_3: 'CYM',
                    },
                    {
                        id: 41,
                        name_en: 'Central African Republic',
                        name_ar: 'جمهورية أفريقيا الوسطى',
                        country_code: 236,
                        iso_code_2: 'CF',
                        iso_code_3: 'CAF',
                    },
                    {
                        id: 42,
                        name_en: 'Chad',
                        name_ar: 'تشاد',
                        country_code: 235,
                        iso_code_2: 'TD',
                        iso_code_3: 'TCD',
                    },
                    {
                        id: 43,
                        name_en: 'Chile',
                        name_ar: 'تشيلي',
                        country_code: 56,
                        iso_code_2: 'CL',
                        iso_code_3: 'CHL',
                    },
                    {
                        id: 44,
                        name_en: 'China',
                        name_ar: 'الصين',
                        country_code: 86,
                        iso_code_2: 'CN',
                        iso_code_3: 'CHN',
                    },
                    {
                        id: 45,
                        name_en: 'Christmas Island',
                        name_ar: 'جزيرة كريسماس',
                        country_code: 0,
                        iso_code_2: 'CX',
                        iso_code_3: 'CXR',
                    },
                    {
                        id: 46,
                        name_en: 'Cocos (Keeling) Islands',
                        name_ar: 'جزر كوكوس (كيلينغ)',
                        country_code: 0,
                        iso_code_2: 'CC',
                        iso_code_3: 'CCK',
                    },
                    {
                        id: 47,
                        name_en: 'Colombia',
                        name_ar: 'كولومبيا',
                        country_code: 57,
                        iso_code_2: 'CO',
                        iso_code_3: 'COL',
                    },
                    {
                        id: 48,
                        name_en: 'Comoros',
                        name_ar: 'جزر القمر',
                        country_code: 269,
                        iso_code_2: 'KM',
                        iso_code_3: 'COM',
                    },
                    {
                        id: 49,
                        name_en: 'Congo',
                        name_ar: 'الكونغو',
                        country_code: 242,
                        iso_code_2: 'CG',
                        iso_code_3: 'COG',
                    },
                    {
                        id: 50,
                        name_en: 'Cook Islands',
                        name_ar: 'جزر كوك',
                        country_code: 682,
                        iso_code_2: 'CK',
                        iso_code_3: 'COK',
                    },
                    {
                        id: 51,
                        name_en: 'Costa Rica',
                        name_ar: 'كوستاريكا',
                        country_code: 506,
                        iso_code_2: 'CR',
                        iso_code_3: 'CRI',
                    },
                    {
                        id: 52,
                        name_en: "Cote D'Ivoire",
                        name_ar: 'كوت ديفوار',
                        country_code: 225,
                        iso_code_2: 'CI',
                        iso_code_3: 'CIV',
                    },
                    {
                        id: 53,
                        name_en: 'Croatia',
                        name_ar: 'كرواتيا',
                        country_code: 385,
                        iso_code_2: 'HR',
                        iso_code_3: 'HRV',
                    },
                    {
                        id: 54,
                        name_en: 'Cuba',
                        name_ar: 'كوبا',
                        country_code: 53,
                        iso_code_2: 'CU',
                        iso_code_3: 'CUB',
                    },
                    {
                        id: 55,
                        name_en: 'Cyprus',
                        name_ar: 'قبرص',
                        country_code: 357,
                        iso_code_2: 'CY',
                        iso_code_3: 'CYP',
                    },
                    {
                        id: 56,
                        name_en: 'Czech Republic',
                        name_ar: 'جمهورية التشيك',
                        country_code: 420,
                        iso_code_2: 'CZ',
                        iso_code_3: 'CZE',
                    },
                    {
                        id: 57,
                        name_en: 'Denmark',
                        name_ar: 'الدنمارك',
                        country_code: 45,
                        iso_code_2: 'DK',
                        iso_code_3: 'DNK',
                    },
                    {
                        id: 58,
                        name_en: 'Djibouti',
                        name_ar: 'جيبوتي',
                        country_code: 253,
                        iso_code_2: 'DJ',
                        iso_code_3: 'DJI',
                    },
                    {
                        id: 59,
                        name_en: 'Dominica',
                        name_ar: 'دومينيكا',
                        country_code: 1767,
                        iso_code_2: 'DM',
                        iso_code_3: 'DMA',
                    },
                    {
                        id: 60,
                        name_en: 'Dominican Republic',
                        name_ar: 'جمهورية الدومينيكان',
                        country_code: 1809,
                        iso_code_2: 'DO',
                        iso_code_3: 'DOM',
                    },
                    {
                        id: 61,
                        name_en: 'East Timor',
                        name_ar: 'تيمور الشرقية',
                        country_code: 0,
                        iso_code_2: 'TL',
                        iso_code_3: 'TLS',
                    },
                    {
                        id: 62,
                        name_en: 'Ecuador',
                        name_ar: 'إكوادور',
                        country_code: 593,
                        iso_code_2: 'EC',
                        iso_code_3: 'ECU',
                    },
                    {
                        id: 63,
                        name_en: 'Egypt',
                        name_ar: 'مصر',
                        country_code: 20,
                        iso_code_2: 'EG',
                        iso_code_3: 'EGY',
                    },
                    {
                        id: 64,
                        name_en: 'El Salvador',
                        name_ar: 'السلفادور',
                        country_code: 503,
                        iso_code_2: 'SV',
                        iso_code_3: 'SLV',
                    },
                    {
                        id: 65,
                        name_en: 'Equatorial Guinea',
                        name_ar: 'غينيا الاستوائية',
                        country_code: 240,
                        iso_code_2: 'GQ',
                        iso_code_3: 'GNQ',
                    },
                    {
                        id: 66,
                        name_en: 'Eritrea',
                        name_ar: 'إريتريا',
                        country_code: 291,
                        iso_code_2: 'ER',
                        iso_code_3: 'ERI',
                    },
                    {
                        id: 67,
                        name_en: 'Estonia',
                        name_ar: 'إستونيا',
                        country_code: 372,
                        iso_code_2: 'EE',
                        iso_code_3: 'EST',
                    },
                    {
                        id: 68,
                        name_en: 'Ethiopia',
                        name_ar: 'إثيوبيا',
                        country_code: 251,
                        iso_code_2: 'ET',
                        iso_code_3: 'ETH',
                    },
                    {
                        id: 69,
                        name_en: 'Falkland Islands (Malvinas)',
                        name_ar: 'جزر فوكلاند (مالفيناس)',
                        country_code: 500,
                        iso_code_2: 'FK',
                        iso_code_3: 'FLK',
                    },
                    {
                        id: 70,
                        name_en: 'Faroe Islands',
                        name_ar: 'جزر فارو',
                        country_code: 298,
                        iso_code_2: 'FO',
                        iso_code_3: 'FRO',
                    },
                    {
                        id: 71,
                        name_en: 'Fiji',
                        name_ar: 'فيجي',
                        country_code: 679,
                        iso_code_2: 'FJ',
                        iso_code_3: 'FJI',
                    },
                    {
                        id: 72,
                        name_en: 'Finland',
                        name_ar: 'فنلندا',
                        country_code: 358,
                        iso_code_2: 'FI',
                        iso_code_3: 'FIN',
                    },
                    {
                        id: 74,
                        name_en: 'France, Metropolitan',
                        name_ar: 'فرنسا , متروبوليتان',
                        country_code: 33,
                        iso_code_2: 'FR',
                        iso_code_3: 'FRA',
                    },
                    {
                        id: 75,
                        name_en: 'French Guiana',
                        name_ar: 'غيانا الفرنسية',
                        country_code: 594,
                        iso_code_2: 'GF',
                        iso_code_3: 'GUF',
                    },
                    {
                        id: 76,
                        name_en: 'French Polynesia',
                        name_ar: 'بولينيزيا الفرنسية',
                        country_code: 689,
                        iso_code_2: 'PF',
                        iso_code_3: 'PYF',
                    },
                    {
                        id: 77,
                        name_en: 'French Southern Territories',
                        name_ar: 'الأقاليم الجنوبية الفرنسية',
                        country_code: 0,
                        iso_code_2: 'TF',
                        iso_code_3: 'ATF',
                    },
                    {
                        id: 78,
                        name_en: 'Gabon',
                        name_ar: 'غابون',
                        country_code: 241,
                        iso_code_2: 'GA',
                        iso_code_3: 'GAB',
                    },
                    {
                        id: 79,
                        name_en: 'Gambia',
                        name_ar: 'غامبيا',
                        country_code: 220,
                        iso_code_2: 'GM',
                        iso_code_3: 'GMB',
                    },
                    {
                        id: 80,
                        name_en: 'Georgia',
                        name_ar: 'جورجيا',
                        country_code: 995,
                        iso_code_2: 'GE',
                        iso_code_3: 'GEO',
                    },
                    {
                        id: 81,
                        name_en: 'Germany',
                        name_ar: 'ألمانيا',
                        country_code: 49,
                        iso_code_2: 'DE',
                        iso_code_3: 'DEU',
                    },
                    {
                        id: 82,
                        name_en: 'Ghana',
                        name_ar: 'غانا',
                        country_code: 233,
                        iso_code_2: 'GH',
                        iso_code_3: 'GHA',
                    },
                    {
                        id: 83,
                        name_en: 'Gibraltar',
                        name_ar: 'جبل طارق',
                        country_code: 350,
                        iso_code_2: 'GI',
                        iso_code_3: 'GIB',
                    },
                    {
                        id: 84,
                        name_en: 'Greece',
                        name_ar: 'اليونان',
                        country_code: 30,
                        iso_code_2: 'GR',
                        iso_code_3: 'GRC',
                    },
                    {
                        id: 85,
                        name_en: 'Greenland',
                        name_ar: 'جرينلاند',
                        country_code: 299,
                        iso_code_2: 'GL',
                        iso_code_3: 'GRL',
                    },
                    {
                        id: 86,
                        name_en: 'Grenada',
                        name_ar: 'غرينادا',
                        country_code: 1473,
                        iso_code_2: 'GD',
                        iso_code_3: 'GRD',
                    },
                    {
                        id: 87,
                        name_en: 'Guadeloupe',
                        name_ar: 'جوادلوب',
                        country_code: 590,
                        iso_code_2: 'GP',
                        iso_code_3: 'GLP',
                    },
                    {
                        id: 88,
                        name_en: 'Guam',
                        name_ar: 'غوام',
                        country_code: 1671,
                        iso_code_2: 'GU',
                        iso_code_3: 'GUM',
                    },
                    {
                        id: 89,
                        name_en: 'Guatemala',
                        name_ar: 'غواتيمالا',
                        country_code: 502,
                        iso_code_2: 'GT',
                        iso_code_3: 'GTM',
                    },
                    {
                        id: 90,
                        name_en: 'Guinea',
                        name_ar: 'غينيا',
                        country_code: 224,
                        iso_code_2: 'GN',
                        iso_code_3: 'GIN',
                    },
                    {
                        id: 91,
                        name_en: 'Guinea-Bissau',
                        name_ar: 'غينيا بيساو',
                        country_code: 245,
                        iso_code_2: 'GW',
                        iso_code_3: 'GNB',
                    },
                    {
                        id: 92,
                        name_en: 'Guyana',
                        name_ar: 'غيانا',
                        country_code: 592,
                        iso_code_2: 'GY',
                        iso_code_3: 'GUY',
                    },
                    {
                        id: 93,
                        name_en: 'Haiti',
                        name_ar: 'هايتي',
                        country_code: 509,
                        iso_code_2: 'HT',
                        iso_code_3: 'HTI',
                    },
                    {
                        id: 94,
                        name_en: 'Heard and Mc Donald Islands',
                        name_ar: 'جزر هيرد وماكدونالد',
                        country_code: 0,
                        iso_code_2: 'HM',
                        iso_code_3: 'HMD',
                    },
                    {
                        id: 95,
                        name_en: 'Honduras',
                        name_ar: 'هندوراس',
                        country_code: 504,
                        iso_code_2: 'HN',
                        iso_code_3: 'HND',
                    },
                    {
                        id: 96,
                        name_en: 'Hong Kong',
                        name_ar: 'هونج كونج',
                        country_code: 852,
                        iso_code_2: 'HK',
                        iso_code_3: 'HKG',
                    },
                    {
                        id: 97,
                        name_en: 'Hungary',
                        name_ar: 'المجر',
                        country_code: 36,
                        iso_code_2: 'HU',
                        iso_code_3: 'HUN',
                    },
                    {
                        id: 98,
                        name_en: 'Iceland',
                        name_ar: 'أيسلندا',
                        country_code: 354,
                        iso_code_2: 'IS',
                        iso_code_3: 'ISL',
                    },
                    {
                        id: 99,
                        name_en: 'India',
                        name_ar: 'الهند',
                        country_code: 91,
                        iso_code_2: 'IN',
                        iso_code_3: 'IND',
                    },
                    {
                        id: 100,
                        name_en: 'Indonesia',
                        name_ar: 'إندونيسيا',
                        country_code: 62,
                        iso_code_2: 'ID',
                        iso_code_3: 'IDN',
                    },
                    {
                        id: 101,
                        name_en: 'Iran (Islamic Republic of)',
                        name_ar: 'جمهورية إيران الإسلامية',
                        country_code: 98,
                        iso_code_2: 'IR',
                        iso_code_3: 'IRN',
                    },
                    {
                        id: 102,
                        name_en: 'Iraq',
                        name_ar: 'العراق',
                        country_code: 964,
                        iso_code_2: 'IQ',
                        iso_code_3: 'IRQ',
                    },
                    {
                        id: 103,
                        name_en: 'Ireland',
                        name_ar: 'أيرلندا',
                        country_code: 353,
                        iso_code_2: 'IE',
                        iso_code_3: 'IRL',
                    },
                    {
                        id: 105,
                        name_en: 'Italy',
                        name_ar: 'إيطاليا',
                        country_code: 39,
                        iso_code_2: 'IT',
                        iso_code_3: 'ITA',
                    },
                    {
                        id: 106,
                        name_en: 'Jamaica',
                        name_ar: 'جامايكا',
                        country_code: 1876,
                        iso_code_2: 'JM',
                        iso_code_3: 'JAM',
                    },
                    {
                        id: 107,
                        name_en: 'Japan',
                        name_ar: 'اليابان',
                        country_code: 81,
                        iso_code_2: 'JP',
                        iso_code_3: 'JPN',
                    },
                    {
                        id: 108,
                        name_en: 'Jordan',
                        name_ar: 'الأردن',
                        country_code: 962,
                        iso_code_2: 'JO',
                        iso_code_3: 'JOR',
                    },
                    {
                        id: 109,
                        name_en: 'Kazakhstan',
                        name_ar: 'كازاخستان',
                        country_code: 7,
                        iso_code_2: 'KZ',
                        iso_code_3: 'KAZ',
                    },
                    {
                        id: 110,
                        name_en: 'Kenya',
                        name_ar: 'كينيا',
                        country_code: 254,
                        iso_code_2: 'KE',
                        iso_code_3: 'KEN',
                    },
                    {
                        id: 111,
                        name_en: 'Kiribati',
                        name_ar: 'كيريباتي',
                        country_code: 686,
                        iso_code_2: 'KI',
                        iso_code_3: 'KIR',
                    },
                    {
                        id: 112,
                        name_en: 'North Korea',
                        name_ar: 'كوريا الشمالية',
                        country_code: 850,
                        iso_code_2: 'KP',
                        iso_code_3: 'PRK',
                    },
                    {
                        id: 113,
                        name_en: 'South Korea',
                        name_ar: 'كوريا الجنوبية',
                        country_code: 82,
                        iso_code_2: 'KR',
                        iso_code_3: 'KOR',
                    },
                    {
                        id: 114,
                        name_en: 'Kuwait',
                        name_ar: 'الكويت',
                        country_code: 965,
                        iso_code_2: 'KW',
                        iso_code_3: 'KWT',
                    },
                    {
                        id: 115,
                        name_en: 'Kyrgyzstan',
                        name_ar: 'قيرغيزستان',
                        country_code: 996,
                        iso_code_2: 'KG',
                        iso_code_3: 'KGZ',
                    },
                    {
                        id: 116,
                        name_en: "Lao People's Democratic Republic",
                        name_ar: 'جمهورية لاو الديمقراطية الشعبية',
                        country_code: 856,
                        iso_code_2: 'LA',
                        iso_code_3: 'LAO',
                    },
                    {
                        id: 117,
                        name_en: 'Latvia',
                        name_ar: 'لاتفيا',
                        country_code: 371,
                        iso_code_2: 'LV',
                        iso_code_3: 'LVA',
                    },
                    {
                        id: 118,
                        name_en: 'Lebanon',
                        name_ar: 'لبنان',
                        country_code: 961,
                        iso_code_2: 'LB',
                        iso_code_3: 'LBN',
                    },
                    {
                        id: 119,
                        name_en: 'Lesotho',
                        name_ar: 'ليسوتو',
                        country_code: 266,
                        iso_code_2: 'LS',
                        iso_code_3: 'LSO',
                    },
                    {
                        id: 120,
                        name_en: 'Liberia',
                        name_ar: 'ليبيريا',
                        country_code: 231,
                        iso_code_2: 'LR',
                        iso_code_3: 'LBR',
                    },
                    {
                        id: 121,
                        name_en: 'Libyan Arab Jamahiriya',
                        name_ar: 'الجماهيرية العربية الليبية',
                        country_code: 218,
                        iso_code_2: 'LY',
                        iso_code_3: 'LBY',
                    },
                    {
                        id: 122,
                        name_en: 'Liechtenstein',
                        name_ar: 'ليختنشتاين',
                        country_code: 423,
                        iso_code_2: 'LI',
                        iso_code_3: 'LIE',
                    },
                    {
                        id: 123,
                        name_en: 'Lithuania',
                        name_ar: 'ليتوانيا',
                        country_code: 370,
                        iso_code_2: 'LT',
                        iso_code_3: 'LTU',
                    },
                    {
                        id: 124,
                        name_en: 'Luxembourg',
                        name_ar: 'لوكسمبورغ',
                        country_code: 352,
                        iso_code_2: 'LU',
                        iso_code_3: 'LUX',
                    },
                    {
                        id: 125,
                        name_en: 'Macau',
                        name_ar: 'ماكاو',
                        country_code: 853,
                        iso_code_2: 'MO',
                        iso_code_3: 'MAC',
                    },
                    {
                        id: 126,
                        name_en: 'North Macedonia',
                        name_ar: 'مقدونيا الشمالية',
                        country_code: 389,
                        iso_code_2: 'MK',
                        iso_code_3: 'MKD',
                    },
                    {
                        id: 127,
                        name_en: 'Madagascar',
                        name_ar: 'مدغشقر',
                        country_code: 261,
                        iso_code_2: 'MG',
                        iso_code_3: 'MDG',
                    },
                    {
                        id: 128,
                        name_en: 'Malawi',
                        name_ar: 'ملاوي',
                        country_code: 265,
                        iso_code_2: 'MW',
                        iso_code_3: 'MWI',
                    },
                    {
                        id: 129,
                        name_en: 'Malaysia',
                        name_ar: 'ماليزيا',
                        country_code: 60,
                        iso_code_2: 'MY',
                        iso_code_3: 'MYS',
                    },
                    {
                        id: 130,
                        name_en: 'Maldives',
                        name_ar: 'جزر المالديف',
                        country_code: 960,
                        iso_code_2: 'MV',
                        iso_code_3: 'MDV',
                    },
                    {
                        id: 131,
                        name_en: 'Mali',
                        name_ar: 'مالي',
                        country_code: 223,
                        iso_code_2: 'ML',
                        iso_code_3: 'MLI',
                    },
                    {
                        id: 132,
                        name_en: 'Malta',
                        name_ar: 'مالطا',
                        country_code: 356,
                        iso_code_2: 'MT',
                        iso_code_3: 'MLT',
                    },
                    {
                        id: 133,
                        name_en: 'Marshall Islands',
                        name_ar: 'جزر مارشال',
                        country_code: 692,
                        iso_code_2: 'MH',
                        iso_code_3: 'MHL',
                    },
                    {
                        id: 134,
                        name_en: 'Martinique',
                        name_ar: 'مارتينيك',
                        country_code: 596,
                        iso_code_2: 'MQ',
                        iso_code_3: 'MTQ',
                    },
                    {
                        id: 135,
                        name_en: 'Mauritania',
                        name_ar: 'موريتانيا',
                        country_code: 222,
                        iso_code_2: 'MR',
                        iso_code_3: 'MRT',
                    },
                    {
                        id: 136,
                        name_en: 'Mauritius',
                        name_ar: 'موريشيوس',
                        country_code: 230,
                        iso_code_2: 'MU',
                        iso_code_3: 'MUS',
                    },
                    {
                        id: 137,
                        name_en: 'Mayotte',
                        name_ar: 'مايوت',
                        country_code: 0,
                        iso_code_2: 'YT',
                        iso_code_3: 'MYT',
                    },
                    {
                        id: 138,
                        name_en: 'Mexico',
                        name_ar: 'المكسيك',
                        country_code: 52,
                        iso_code_2: 'MX',
                        iso_code_3: 'MEX',
                    },
                    {
                        id: 139,
                        name_en: 'Micronesia, Federated States of',
                        name_ar: 'ميكرونيزيا , ولايات - الموحدة',
                        country_code: 691,
                        iso_code_2: 'FM',
                        iso_code_3: 'FSM',
                    },
                    {
                        id: 140,
                        name_en: 'Moldova, Republic of',
                        name_ar: 'مولدوفا , جمهورية',
                        country_code: 373,
                        iso_code_2: 'MD',
                        iso_code_3: 'MDA',
                    },
                    {
                        id: 141,
                        name_en: 'Monaco',
                        name_ar: 'موناكو',
                        country_code: 377,
                        iso_code_2: 'MC',
                        iso_code_3: 'MCO',
                    },
                    {
                        id: 142,
                        name_en: 'Mongolia',
                        name_ar: 'منغوليا',
                        country_code: 976,
                        iso_code_2: 'MN',
                        iso_code_3: 'MNG',
                    },
                    {
                        id: 143,
                        name_en: 'Montserrat',
                        name_ar: 'مونتسيرات',
                        country_code: 1664,
                        iso_code_2: 'MS',
                        iso_code_3: 'MSR',
                    },
                    {
                        id: 144,
                        name_en: 'Morocco',
                        name_ar: 'المغرب',
                        country_code: 212,
                        iso_code_2: 'MA',
                        iso_code_3: 'MAR',
                    },
                    {
                        id: 145,
                        name_en: 'Mozambique',
                        name_ar: 'موزمبيق',
                        country_code: 258,
                        iso_code_2: 'MZ',
                        iso_code_3: 'MOZ',
                    },
                    {
                        id: 146,
                        name_en: 'Myanmar',
                        name_ar: 'ميانمار',
                        country_code: 95,
                        iso_code_2: 'MM',
                        iso_code_3: 'MMR',
                    },
                    {
                        id: 147,
                        name_en: 'Namibia',
                        name_ar: 'ناميبيا',
                        country_code: 264,
                        iso_code_2: 'NA',
                        iso_code_3: 'NAM',
                    },
                    {
                        id: 148,
                        name_en: 'Nauru',
                        name_ar: 'ناورو',
                        country_code: 674,
                        iso_code_2: 'NR',
                        iso_code_3: 'NRU',
                    },
                    {
                        id: 149,
                        name_en: 'Nepal',
                        name_ar: 'نيبال',
                        country_code: 977,
                        iso_code_2: 'NP',
                        iso_code_3: 'NPL',
                    },
                    {
                        id: 150,
                        name_en: 'Netherlands',
                        name_ar: 'هولندا',
                        country_code: 31,
                        iso_code_2: 'NL',
                        iso_code_3: 'NLD',
                    },
                    {
                        id: 151,
                        name_en: 'Netherlands Antilles',
                        name_ar: 'جزر الأنتيل الهولندية',
                        country_code: 599,
                        iso_code_2: 'AN',
                        iso_code_3: 'ANT',
                    },
                    {
                        id: 152,
                        name_en: 'New Caledonia',
                        name_ar: 'كاليدونيا الجديدة',
                        country_code: 687,
                        iso_code_2: 'NC',
                        iso_code_3: 'NCL',
                    },
                    {
                        id: 153,
                        name_en: 'New Zealand',
                        name_ar: 'نيوزيلندا',
                        country_code: 64,
                        iso_code_2: 'NZ',
                        iso_code_3: 'NZL',
                    },
                    {
                        id: 154,
                        name_en: 'Nicaragua',
                        name_ar: 'نيكاراغوا',
                        country_code: 505,
                        iso_code_2: 'NI',
                        iso_code_3: 'NIC',
                    },
                    {
                        id: 155,
                        name_en: 'Niger',
                        name_ar: 'النيجر',
                        country_code: 227,
                        iso_code_2: 'NE',
                        iso_code_3: 'NER',
                    },
                    {
                        id: 156,
                        name_en: 'Nigeria',
                        name_ar: 'نيجيريا',
                        country_code: 234,
                        iso_code_2: 'NG',
                        iso_code_3: 'NGA',
                    },
                    {
                        id: 157,
                        name_en: 'Niue',
                        name_ar: 'نيوي',
                        country_code: 683,
                        iso_code_2: 'NU',
                        iso_code_3: 'NIU',
                    },
                    {
                        id: 158,
                        name_en: 'Norfolk Island',
                        name_ar: 'جزيرة نورفولك',
                        country_code: 672,
                        iso_code_2: 'NF',
                        iso_code_3: 'NFK',
                    },
                    {
                        id: 159,
                        name_en: 'Northern Mariana Islands',
                        name_ar: 'جزر ماريانا الشمالية',
                        country_code: 1670,
                        iso_code_2: 'MP',
                        iso_code_3: 'MNP',
                    },
                    {
                        id: 160,
                        name_en: 'Norway',
                        name_ar: 'النرويج',
                        country_code: 47,
                        iso_code_2: 'NO',
                        iso_code_3: 'NOR',
                    },
                    {
                        id: 161,
                        name_en: 'Oman',
                        name_ar: 'عمان',
                        country_code: 968,
                        iso_code_2: 'OM',
                        iso_code_3: 'OMN',
                    },
                    {
                        id: 162,
                        name_en: 'Pakistan',
                        name_ar: 'باكستان',
                        country_code: 92,
                        iso_code_2: 'PK',
                        iso_code_3: 'PAK',
                    },
                    {
                        id: 163,
                        name_en: 'Palau',
                        name_ar: 'بالاو',
                        country_code: 680,
                        iso_code_2: 'PW',
                        iso_code_3: 'PLW',
                    },
                    {
                        id: 164,
                        name_en: 'Panama',
                        name_ar: 'بنما',
                        country_code: 507,
                        iso_code_2: 'PA',
                        iso_code_3: 'PAN',
                    },
                    {
                        id: 165,
                        name_en: 'Papua New Guinea',
                        name_ar: 'بابوا غينيا الجديدة',
                        country_code: 675,
                        iso_code_2: 'PG',
                        iso_code_3: 'PNG',
                    },
                    {
                        id: 166,
                        name_en: 'Paraguay',
                        name_ar: 'باراجواي',
                        country_code: 595,
                        iso_code_2: 'PY',
                        iso_code_3: 'PRY',
                    },
                    {
                        id: 167,
                        name_en: 'Peru',
                        name_ar: 'بيرو',
                        country_code: 51,
                        iso_code_2: 'PE',
                        iso_code_3: 'PER',
                    },
                    {
                        id: 168,
                        name_en: 'Philippines',
                        name_ar: 'الفلبين',
                        country_code: 63,
                        iso_code_2: 'PH',
                        iso_code_3: 'PHL',
                    },
                    {
                        id: 169,
                        name_en: 'Pitcairn',
                        name_ar: 'بيتكيرن',
                        country_code: 0,
                        iso_code_2: 'PN',
                        iso_code_3: 'PCN',
                    },
                    {
                        id: 170,
                        name_en: 'Poland',
                        name_ar: 'بولندا',
                        country_code: 48,
                        iso_code_2: 'PL',
                        iso_code_3: 'POL',
                    },
                    {
                        id: 171,
                        name_en: 'Portugal',
                        name_ar: 'البرتغال',
                        country_code: 351,
                        iso_code_2: 'PT',
                        iso_code_3: 'PRT',
                    },
                    {
                        id: 172,
                        name_en: 'Puerto Rico',
                        name_ar: 'بورتوريكو',
                        country_code: 1787,
                        iso_code_2: 'PR',
                        iso_code_3: 'PRI',
                    },
                    {
                        id: 173,
                        name_en: 'Qatar',
                        name_ar: 'قطر',
                        country_code: 974,
                        iso_code_2: 'QA',
                        iso_code_3: 'QAT',
                    },
                    {
                        id: 174,
                        name_en: 'Reunion',
                        name_ar: 'ريونيون',
                        country_code: 262,
                        iso_code_2: 'RE',
                        iso_code_3: 'REU',
                    },
                    {
                        id: 175,
                        name_en: 'Romania',
                        name_ar: 'رومانيا',
                        country_code: 40,
                        iso_code_2: 'RO',
                        iso_code_3: 'ROM',
                    },
                    {
                        id: 176,
                        name_en: 'Russian Federation',
                        name_ar: 'الاتحاد الروسي',
                        country_code: 70,
                        iso_code_2: 'RU',
                        iso_code_3: 'RUS',
                    },
                    {
                        id: 177,
                        name_en: 'Rwanda',
                        name_ar: 'رواندا',
                        country_code: 250,
                        iso_code_2: 'RW',
                        iso_code_3: 'RWA',
                    },
                    {
                        id: 178,
                        name_en: 'Saint Kitts and Nevis',
                        name_ar: 'سانت كيتس ونيفيس',
                        country_code: 1869,
                        iso_code_2: 'KN',
                        iso_code_3: 'KNA',
                    },
                    {
                        id: 179,
                        name_en: 'Saint Lucia',
                        name_ar: 'سانت لوسيا',
                        country_code: 1758,
                        iso_code_2: 'LC',
                        iso_code_3: 'LCA',
                    },
                    {
                        id: 180,
                        name_en: 'Saint Vincent and the Grenadines',
                        name_ar: 'سانت فنسنت وجزر غرينادين',
                        country_code: 1784,
                        iso_code_2: 'VC',
                        iso_code_3: 'VCT',
                    },
                    {
                        id: 181,
                        name_en: 'Samoa',
                        name_ar: 'ساموا',
                        country_code: 684,
                        iso_code_2: 'WS',
                        iso_code_3: 'WSM',
                    },
                    {
                        id: 182,
                        name_en: 'San Marino',
                        name_ar: 'سان مارينو',
                        country_code: 378,
                        iso_code_2: 'SM',
                        iso_code_3: 'SMR',
                    },
                    {
                        id: 183,
                        name_en: 'Sao Tome and Principe',
                        name_ar: 'سان تومي وبرينسيبي',
                        country_code: 239,
                        iso_code_2: 'ST',
                        iso_code_3: 'STP',
                    },
                    {
                        id: 184,
                        name_en: 'Saudi Arabia',
                        name_ar: 'المملكة العربية السعودية',
                        country_code: 966,
                        iso_code_2: 'SA',
                        iso_code_3: 'SAU',
                    },
                    {
                        id: 185,
                        name_en: 'Senegal',
                        name_ar: 'السنغال',
                        country_code: 221,
                        iso_code_2: 'SN',
                        iso_code_3: 'SEN',
                    },
                    {
                        id: 186,
                        name_en: 'Seychelles',
                        name_ar: 'سيشيل',
                        country_code: 248,
                        iso_code_2: 'SC',
                        iso_code_3: 'SYC',
                    },
                    {
                        id: 187,
                        name_en: 'Sierra Leone',
                        name_ar: 'سيراليون',
                        country_code: 232,
                        iso_code_2: 'SL',
                        iso_code_3: 'SLE',
                    },
                    {
                        id: 188,
                        name_en: 'Singapore',
                        name_ar: 'سنغافورة',
                        country_code: 65,
                        iso_code_2: 'SG',
                        iso_code_3: 'SGP',
                    },
                    {
                        id: 189,
                        name_en: 'Slovak Republic',
                        name_ar: 'الجمهورية السلوفاكية',
                        country_code: 421,
                        iso_code_2: 'SK',
                        iso_code_3: 'SVK',
                    },
                    {
                        id: 190,
                        name_en: 'Slovenia',
                        name_ar: 'سلوفينيا',
                        country_code: 386,
                        iso_code_2: 'SI',
                        iso_code_3: 'SVN',
                    },
                    {
                        id: 191,
                        name_en: 'Solomon Islands',
                        name_ar: 'جزر سليمان',
                        country_code: 677,
                        iso_code_2: 'SB',
                        iso_code_3: 'SLB',
                    },
                    {
                        id: 192,
                        name_en: 'Somalia',
                        name_ar: 'الصومال',
                        country_code: 252,
                        iso_code_2: 'SO',
                        iso_code_3: 'SOM',
                    },
                    {
                        id: 193,
                        name_en: 'South Africa',
                        name_ar: 'جنوب إفريقيا',
                        country_code: 27,
                        iso_code_2: 'ZA',
                        iso_code_3: 'ZAF',
                    },
                    {
                        id: 194,
                        name_en: 'South Georgia & South Sandwich Islands',
                        name_ar: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
                        country_code: 0,
                        iso_code_2: 'GS',
                        iso_code_3: 'SGS',
                    },
                    {
                        id: 195,
                        name_en: 'Spain',
                        name_ar: 'إسبانيا',
                        country_code: 34,
                        iso_code_2: 'ES',
                        iso_code_3: 'ESP',
                    },
                    {
                        id: 196,
                        name_en: 'Sri Lanka',
                        name_ar: 'سري لانكا',
                        country_code: 94,
                        iso_code_2: 'LK',
                        iso_code_3: 'LKA',
                    },
                    {
                        id: 197,
                        name_en: 'St. Helena',
                        name_ar: 'سانت هيلانة',
                        country_code: 290,
                        iso_code_2: 'SH',
                        iso_code_3: 'SHN',
                    },
                    {
                        id: 198,
                        name_en: 'St. Pierre and Miquelon',
                        name_ar: 'سانت بيير وميكلون',
                        country_code: 508,
                        iso_code_2: 'PM',
                        iso_code_3: 'SPM',
                    },
                    {
                        id: 199,
                        name_en: 'Sudan',
                        name_ar: 'السودان',
                        country_code: 249,
                        iso_code_2: 'SD',
                        iso_code_3: 'SDN',
                    },
                    {
                        id: 200,
                        name_en: 'Suriname',
                        name_ar: 'سورينام',
                        country_code: 597,
                        iso_code_2: 'SR',
                        iso_code_3: 'SUR',
                    },
                    {
                        id: 201,
                        name_en: 'Svalbard and Jan Mayen Islands',
                        name_ar: 'جزر سفالبارد وجان ماين',
                        country_code: 47,
                        iso_code_2: 'SJ',
                        iso_code_3: 'SJM',
                    },
                    {
                        id: 202,
                        name_en: 'Swaziland',
                        name_ar: 'سوازيلند',
                        country_code: 268,
                        iso_code_2: 'SZ',
                        iso_code_3: 'SWZ',
                    },
                    {
                        id: 203,
                        name_en: 'Sweden',
                        name_ar: 'السويد',
                        country_code: 46,
                        iso_code_2: 'SE',
                        iso_code_3: 'SWE',
                    },
                    {
                        id: 204,
                        name_en: 'Switzerland',
                        name_ar: 'سويسرا',
                        country_code: 41,
                        iso_code_2: 'CH',
                        iso_code_3: 'CHE',
                    },
                    {
                        id: 205,
                        name_en: 'Syrian Arab Republic',
                        name_ar: 'الجمهورية العربية السورية',
                        country_code: 963,
                        iso_code_2: 'SY',
                        iso_code_3: 'SYR',
                    },
                    {
                        id: 206,
                        name_en: 'Taiwan',
                        name_ar: 'تايوان',
                        country_code: 886,
                        iso_code_2: 'TW',
                        iso_code_3: 'TWN',
                    },
                    {
                        id: 207,
                        name_en: 'Tajikistan',
                        name_ar: 'طاجيكستان',
                        country_code: 992,
                        iso_code_2: 'TJ',
                        iso_code_3: 'TJK',
                    },
                    {
                        id: 208,
                        name_en: 'Tanzania, United Republic of',
                        name_ar: 'جمهورية تنزانيا المتحدة',
                        country_code: 255,
                        iso_code_2: 'TZ',
                        iso_code_3: 'TZA',
                    },
                    {
                        id: 209,
                        name_en: 'Thailand',
                        name_ar: 'تايلاند',
                        country_code: 66,
                        iso_code_2: 'TH',
                        iso_code_3: 'THA',
                    },
                    {
                        id: 210,
                        name_en: 'Togo',
                        name_ar: 'توغو',
                        country_code: 228,
                        iso_code_2: 'TG',
                        iso_code_3: 'TGO',
                    },
                    {
                        id: 211,
                        name_en: 'Tokelau',
                        name_ar: 'توكيلاو',
                        country_code: 690,
                        iso_code_2: 'TK',
                        iso_code_3: 'TKL',
                    },
                    {
                        id: 212,
                        name_en: 'Tonga',
                        name_ar: 'تونجا',
                        country_code: 676,
                        iso_code_2: 'TO',
                        iso_code_3: 'TON',
                    },
                    {
                        id: 213,
                        name_en: 'Trinidad and Tobago',
                        name_ar: 'ترينيداد وتوباغو',
                        country_code: 1868,
                        iso_code_2: 'TT',
                        iso_code_3: 'TTO',
                    },
                    {
                        id: 214,
                        name_en: 'Tunisia',
                        name_ar: 'تونس',
                        country_code: 216,
                        iso_code_2: 'TN',
                        iso_code_3: 'TUN',
                    },
                    {
                        id: 215,
                        name_en: 'Turkey',
                        name_ar: 'تركيا',
                        country_code: 90,
                        iso_code_2: 'TR',
                        iso_code_3: 'TUR',
                    },
                    {
                        id: 216,
                        name_en: 'Turkmenistan',
                        name_ar: 'تركمانستان',
                        country_code: 7370,
                        iso_code_2: 'TM',
                        iso_code_3: 'TKM',
                    },
                    {
                        id: 217,
                        name_en: 'Turks and Caicos Islands',
                        name_ar: 'جزر تركس وكايكوس',
                        country_code: 1649,
                        iso_code_2: 'TC',
                        iso_code_3: 'TCA',
                    },
                    {
                        id: 218,
                        name_en: 'Tuvalu',
                        name_ar: 'توفالو',
                        country_code: 688,
                        iso_code_2: 'TV',
                        iso_code_3: 'TUV',
                    },
                    {
                        id: 219,
                        name_en: 'Uganda',
                        name_ar: 'أوغندا',
                        country_code: 256,
                        iso_code_2: 'UG',
                        iso_code_3: 'UGA',
                    },
                    {
                        id: 220,
                        name_en: 'Ukraine',
                        name_ar: 'أوكرانيا',
                        country_code: 380,
                        iso_code_2: 'UA',
                        iso_code_3: 'UKR',
                    },
                    {
                        id: 221,
                        name_en: 'United Arab Emirates',
                        name_ar: 'الإمارات العربية المتحدة',
                        country_code: 971,
                        iso_code_2: 'AE',
                        iso_code_3: 'ARE',
                    },
                    {
                        id: 222,
                        name_en: 'United Kingdom',
                        name_ar: 'المملكة المتحدة',
                        country_code: 44,
                        iso_code_2: 'GB',
                        iso_code_3: 'GBR',
                    },
                    {
                        id: 223,
                        name_en: 'United States',
                        name_ar: 'الولايات المتحدة',
                        country_code: 1,
                        iso_code_2: 'US',
                        iso_code_3: 'USA',
                    },
                    {
                        id: 224,
                        name_en: 'United States Minor Outlying Islands',
                        name_ar: 'جزر الولايات المتحدة البعيدة الصغيرة',
                        country_code: 0,
                        iso_code_2: 'UM',
                        iso_code_3: 'UMI',
                    },
                    {
                        id: 225,
                        name_en: 'Uruguay',
                        name_ar: 'أوروغواي',
                        country_code: 598,
                        iso_code_2: 'UY',
                        iso_code_3: 'URY',
                    },
                    {
                        id: 226,
                        name_en: 'Uzbekistan',
                        name_ar: 'أوزبكستان',
                        country_code: 998,
                        iso_code_2: 'UZ',
                        iso_code_3: 'UZB',
                    },
                    {
                        id: 227,
                        name_en: 'Vanuatu',
                        name_ar: 'فانواتو',
                        country_code: 678,
                        iso_code_2: 'VU',
                        iso_code_3: 'VUT',
                    },
                    {
                        id: 228,
                        name_en: 'Vatican City State (Holy See)',
                        name_ar: 'دولة مدينة الفاتيكان (الكرسي الرسولي)',
                        country_code: 39,
                        iso_code_2: 'VA',
                        iso_code_3: 'VAT',
                    },
                    {
                        id: 229,
                        name_en: 'Venezuela',
                        name_ar: 'فنزويلا',
                        country_code: 58,
                        iso_code_2: 'VE',
                        iso_code_3: 'VEN',
                    },
                    {
                        id: 230,
                        name_en: 'Viet Nam',
                        name_ar: 'فييت نام',
                        country_code: 84,
                        iso_code_2: 'VN',
                        iso_code_3: 'VNM',
                    },
                    {
                        id: 231,
                        name_en: 'Virgin Islands (British)',
                        name_ar: 'جزر فيرجن (البريطانية)',
                        country_code: 1284,
                        iso_code_2: 'VG',
                        iso_code_3: 'VGB',
                    },
                    {
                        id: 232,
                        name_en: 'Virgin Islands (U.S.)',
                        name_ar: 'جزر فيرجن (الولايات المتحدة)',
                        country_code: 1340,
                        iso_code_2: 'VI',
                        iso_code_3: 'VIR',
                    },
                    {
                        id: 233,
                        name_en: 'Wallis and Futuna Islands',
                        name_ar: 'جزر واليس وفوتونا',
                        country_code: 681,
                        iso_code_2: 'WF',
                        iso_code_3: 'WLF',
                    },
                    {
                        id: 234,
                        name_en: 'Western Sahara',
                        name_ar: 'الصحراء الغربية',
                        country_code: 212,
                        iso_code_2: 'EH',
                        iso_code_3: 'ESH',
                    },
                    {
                        id: 235,
                        name_en: 'Yemen',
                        name_ar: 'اليمن',
                        country_code: 967,
                        iso_code_2: 'YE',
                        iso_code_3: 'YEM',
                    },
                    {
                        id: 237,
                        name_en: 'Democratic Republic of Congo',
                        name_ar: 'جمهورية الكونغو الديمقراطية',
                        country_code: 242,
                        iso_code_2: 'CD',
                        iso_code_3: 'COD',
                    },
                    {
                        id: 238,
                        name_en: 'Zambia',
                        name_ar: 'زامبيا',
                        country_code: 260,
                        iso_code_2: 'ZM',
                        iso_code_3: 'ZMB',
                    },
                    {
                        id: 239,
                        name_en: 'Zimbabwe',
                        name_ar: 'زيمبابوي',
                        country_code: 263,
                        iso_code_2: 'ZW',
                        iso_code_3: 'ZWE',
                    },
                    {
                        id: 242,
                        name_en: 'Montenegro',
                        name_ar: 'الجبل الأسود',
                        country_code: 0,
                        iso_code_2: 'ME',
                        iso_code_3: 'MNE',
                    },
                    {
                        id: 243,
                        name_en: 'Serbia',
                        name_ar: 'صربيا',
                        country_code: 0,
                        iso_code_2: 'RS',
                        iso_code_3: 'SRB',
                    },
                    {
                        id: 244,
                        name_en: 'Aaland Islands',
                        name_ar: 'جزر آلاند',
                        country_code: 0,
                        iso_code_2: 'AX',
                        iso_code_3: 'ALA',
                    },
                    {
                        id: 245,
                        name_en: 'Bonaire, Sint Eustatius and Saba',
                        name_ar: 'بونير , سينت أوستاتيوس وسابا',
                        country_code: 0,
                        iso_code_2: 'BQ',
                        iso_code_3: 'BES',
                    },
                    {
                        id: 246,
                        name_en: 'Curacao',
                        name_ar: 'كوراكاو',
                        country_code: 0,
                        iso_code_2: 'CW',
                        iso_code_3: 'CUW',
                    },
                    {
                        id: 247,
                        name_en: 'Palestinian Territory, Occupied',
                        name_ar: 'الأرض الفلسطينية المحتلة',
                        country_code: 970,
                        iso_code_2: 'PS',
                        iso_code_3: 'PSE',
                    },
                    {
                        id: 248,
                        name_en: 'South Sudan',
                        name_ar: 'جنوب السودان',
                        country_code: 0,
                        iso_code_2: 'SS',
                        iso_code_3: 'SSD',
                    },
                    {
                        id: 249,
                        name_en: 'St. Barthelemy',
                        name_ar: 'سانت بارتيليمي',
                        country_code: 0,
                        iso_code_2: 'BL',
                        iso_code_3: 'BLM',
                    },
                    {
                        id: 250,
                        name_en: 'St. Martin (French part)',
                        name_ar: 'سانت مارتن (الجزء الفرنسي)',
                        country_code: 0,
                        iso_code_2: 'MF',
                        iso_code_3: 'MAF',
                    },
                    {
                        id: 251,
                        name_en: 'Canary Islands',
                        name_ar: 'جزر الكناري',
                        country_code: 0,
                        iso_code_2: 'IC',
                        iso_code_3: 'ICA',
                    },
                    {
                        id: 252,
                        name_en: 'Ascension Island (British)',
                        name_ar: 'جزيرة أسينشن (البريطانية)',
                        country_code: 0,
                        iso_code_2: 'AC',
                        iso_code_3: 'ASC',
                    },
                    {
                        id: 253,
                        name_en: 'Kosovo, Republic of',
                        name_ar: 'كوسوفو , جمهورية',
                        country_code: 0,
                        iso_code_2: 'XK',
                        iso_code_3: 'UNK',
                    },
                    {
                        id: 254,
                        name_en: 'Isle of Man',
                        name_ar: 'جزيرة مان',
                        country_code: 0,
                        iso_code_2: 'IM',
                        iso_code_3: 'IMN',
                    },
                    {
                        id: 255,
                        name_en: 'Tristan da Cunha',
                        name_ar: 'تريستان دا كونها',
                        country_code: 290,
                        iso_code_2: 'TA',
                        iso_code_3: 'SHN',
                    },
                    {
                        id: 256,
                        name_en: 'Guernsey',
                        name_ar: 'غيرنسي',
                        country_code: 0,
                        iso_code_2: 'GG',
                        iso_code_3: 'GGY',
                    },
                    {
                        id: 257,
                        name_en: 'Jersey',
                        name_ar: 'جيرسي',
                        country_code: 0,
                        iso_code_2: 'JE',
                        iso_code_3: 'JEY',
                    },
                ];
                this.countries = res.data.map((res) => {
                    return {
                        name: this.lang == 'ar' ? res.name_ar : res.name_en,
                        id: res.id,
                    };
                });
                // await $fetch(`${this.apiUrl}/api/countries`, {
                //     method: 'GET',
                //     headers: {
                //         "Accept-Language": this.lang,
                //     },
                // }).then((response) => {
                //     this.countries = response.data.map((res) => {
                //         return {
                //             name: this.lang == 'ar' ? res.name_ar : res.name_en,
                //             id: res.id,
                //         };
                //     });
                // });
            },
            async getCity() {
                await $fetch(`${this.apiUrl}/api/cities?country_id=${this.country_id}`, {
                    method: 'GET',
                }).then((response) => {
                    this.cites = response.data.map((res) => {
                        return {
                            name: this.lang == 'ar' ? res.name_ar : res.name_en,
                            id: res.id,
                        };
                    });
                });
            },
        },
    };
</script>
